### PR TITLE
Merge changes from Office-Addin-TaskPane

### PR DESCRIPTION
**Pull request by akrantz**

### CODE REVIEW

**Comment by akrantz** [comment]
@TCourtneyOwen Should Angular be updated to the latest version?

**Comment by TCourtneyOwen** [comment]
Yeah might as well update angular as long as there are no breaking changes

**Comment by akrantz** [comment]
@TCourtneyOwen Simply updating packages will build but the task pane appear blank.

**Comment by akrantz** [comment]
If you can approve, I'll at least merge these changes.

**Pull request merged**
