### PR TITLE
Merge office-addin-taskpane/master

### PR DESCRIPTION
**Pull request by TCourtneyOwen**
Not crazy about how I had to import images here to get things to build

### CODE REVIEW

**Comment by TCourtneyOwen** [comment]
linting is failing - need to look into this

**Comment by TCourtneyOwen** [comment]
linting is failing because image const are not used

**Comment by akrantz** [comment]
I just got the branch and was going to take a look.

**Comment by TCourtneyOwen** [comment]
If I add the following to tsconfig, I can just do a regular import like we do in office-addin-taskpane:  "esModuleInterop": true,

**Review by akrantz — APPROVED** [review]
OK, this looks good now.

**Pull request merged**
