### PR TITLE
Update sideload-msg

### PR DESCRIPTION
**Pull request by ElizabethSamuel-MSFT**
Thank you for your pull request!  Please provide the following information.

---

**Change Description**:

Link to sideload article. Also fix minor typo

1. **Do these changes impact any *npm scripts* commands (in package.json)?** (e.g., running 'npm run start')
    If Yes, briefly describe what is impacted.

2. **Do these changes impact *VS Code debugging* options (launch.json)?**
    If Yes, briefly describe what is impacted.

3. **Do these changes impact *template output*?** (e.g., add/remove file, update file location, update file contents)
    If Yes, briefly describe what is impacted.

4. **Do these changes impact *documentation*?** (e.g., a tutorial on https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins)
    If Yes, briefly describe what is impacted.

If you answered yes to any of these please do the following:
    > Include 'Rick-Kirkham' in the review
    > Make sure the README file is correct

**Validation/testing performed**:

    Describe manual testing done.

### CODE REVIEW

**Review by kwame-ansong — APPROVED** [review]

**Comment by millerds** [comment]
@ElizabethSamuel-MSFT is this change going to be done to the other template repos as well?

**Comment by akrantz** [comment]
Usually changes like this should be make in [Office-Addin-TaskPane](https://github.com/OfficeDev/Office-Addin-TaskPane ) and then merged across the template repos. Rather than make the change here, make it in Office-Addin-TaskPane.

**Comment by ElizabethSamuel-MSFT** [comment]
> @ElizabethSamuel-MSFT is this change going to be done to the other template repos as well?

Yes, I want to. But I wasn't sure about the process.

**Comment by ElizabethSamuel-MSFT** [comment]
> Usually changes like this should be make in [Office-Addin-TaskPane](https://github.com/OfficeDev/Office-Addin-TaskPane) and then merged across the template repos. Rather than make the change here, make it in Office-Addin-TaskPane.

Ok, I'll update there. Are there other repos I should like at to make similar changes?

**Pull request closed without merging**
